<h1>Création de compte</h1>
<form method="POST" action="index.php?route=user-create" id="registerForm">
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required/>
    </fieldset>
    <fieldset>
        <label for="username">Username</label>
        <input type="text" name="username" id="username" required/>
    </fieldset>
    <fieldset>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required/>
    </fieldset>
    <fieldset>
        <label for="confirmPassword">Confirm Password</label>
        <input type="password" name="confirmPassword" id="confirmPassword" required/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit-create" id="submit-create" value="Créer un compte"/>
    </fieldset>
        <input type="hidden" name="formName" id="formName" value="user-create"/>
</form>