<h1>Liste des utilisateurs</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Username</th>
        </tr>
    </thead>
    <tbody>
        <?php
            if (count($data) > 0)
            {
                foreach($data as $user)
                {
                    echo 
                    "<tr>
                        <td>".$user['id']."</td>
                        <td>".$user['email']."</td>
                        <td>".$user['username']."</td>
                    </tr>";
                }
            }
            else
            {
                echo "<tr><td colspan=4>Aucun utilisateur enregistré.</td></tr>";
            }
        ?>
    </tbody>
</table>